name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push

---

# Optional: if you want the scheduled faked commits part updated
jobs:
  ubaid-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate ubaid commits
        run: |
          for i in {1..5}; do
            echo $RANDOM >> ubaid.txt
            git add ubaid.txt
            GIT_COMMITTER_DATE="$(date -d "$((RANDOM % 30 + 1)) days ago")" \
            git commit --date "$(date -d "$((RANDOM % 30 + 1)) days ago")" -m "ubaid commit $i"
          done
          git push
